---
- include_tasks: "{{ ansible_os_family }}/packages.yml"
- include_tasks: "{{ ansible_os_family }}/firewall.yml"
- include_tasks: "{{ ansible_os_family }}/ssl.yml"

- name: 'Install additional packages'
  ansible.builtin.package:
    name: "{{ packages }}"
    state: 'present'
  vars:
    packages:
      - 'nano'
      - 'emacs'
      - 'zip'
      - 'unzip'
      - 'subversion'
      - 'git'

- name: 'Set timezone'
  community.general.timezone:
    name: "{{ linux_ntp.timezone }}"

- name: 'Create Staff group'
  group:
    name: 'staff'
    state: 'present'

- name: 'Add user to Staff'
  user:
    name: "{{ ansible_user|default(lookup('env', 'USER'), True) }}"
    groups: 'staff'
    append: 'yes'

- name: "Create backup directory"
  file:
    path: "/srv/backups"
    state: "directory"
    group: "staff"

- name: "Grant staff permission to srv directory"
  file:
    path:  "/srv"
    state: "directory"
    group: "staff"
    mode:  "u=rwX,g=rwXs,o=rX"
...
