---
- name: Disable root password
  user:
    name: root
    update_password: always
    password: '!'

- name: Add user to Staff
  user: name={{ ansible_user|default(lookup('env', 'USER'), True) }} groups=staff append=yes

- name: Update apt cache
  apt: update_cache=yes

- name: Install aptitude
  apt: name=aptitude state=present

- name: Full upgrade
  apt: upgrade=full

- name: "Install common packages"
  apt:
    name: "{{ packages }}"
    state: "present"
  vars:
    packages:
      - "ufw"
      - "rsync"
      - "ntp"

- name: "Install VMWare tools"
  apt:
    name: "open-vm-tools"
    state: "present"
  when: ansible_product_name is match("VMware")

- name: "Install additional packages"
  apt:
    name: "{{ linux_packages }}"
    state: "present"


- name: Setup Firewall
  include_tasks: firewall.yml

- name: Setup NTP
  include_tasks: ntp.yml

- name: Install SSL Certs
  include_tasks: ssl.yml

- name: Setup cron backup script
  copy: src=backup dest=/etc/cron.daily/backup force=no owner=root group=root mode=0755

- name: Create cron backup directory
  file: path=/etc/cron.daily/backup.d state=directory owner=root group=root mode=0755

- name: "Grant staff permission to srv directory"
  file:
    path:  "/srv"
    state: "directory"
    group: "staff"
    mode:  "u=rwX,g=rwXs,o=rX"

- name: Setup Unattended Upgrades
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="{{ item.regexp }}" line="{{ item.line }}"
  with_items:
  - { regexp: '\$\{distro_codename\}-updates\"\;', line: '    "${distro_id}:${distro_codename}-updates";'         }
  - { regexp: 'InstallOnShutdown',                 line: 'Unattended-Upgrade::InstallOnShutdown "false";'         }
  - { regexp: 'Remove-Unused-Dependencies',        line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";' }
  - { regexp: 'Automatic-Reboot\s',                line: 'Unattended-Upgrade::Automatic-Reboot "true";'           }
  - { regexp: 'Automatic-Reboot-Time',             line: 'Unattended-Upgrade::Automatic-Reboot-Time "02:00";'     }
...
