---
- name: "Install any custom SSL certs"
  copy:
    content: "{{ item.data }}"
    dest: "/usr/local/share/ca-certificates/{{ item.filename }}"
    force: "yes"
  with_items: "{{ linux_ssl_certs }}"
  no_log: "yes"
  notify: "linux_ssl_update_certs"
...
