---
- name: Create certificates directory
  file: path=/usr/local/share/ca-certificates state=directory

- name: Install any custom SSL certs
  copy:
    content: "{{ item.data }}"
    dest: /usr/local/share/ca-certificates/{{ item.filename }}
  with_items: "{{ ssl_certs | default([]) }}"
  no_log: True
  notify: linux_ssl_update_certs
