---
- name: "Install Debian packages"
  apt:
    name: "{{ packages }}"
    state: "latest"
  vars:
    packages:
      - "aptitude"
      - "ufw"
      - "rsync"
      - "ntp"
      - "language-pack-en"

- name: "Full upgrade"
  apt:
    update_cache: "yes"
    upgrade: "full"

- name: "Install VMWare tools"
  apt:
    name: "open-vm-tools"
    state: "latest"
  when: ansible_product_name is match("VMware")

- name: 'Setup Unattended Upgrades'
  ansible.builtin.lineinfile:
    path:   '/etc/apt/apt.conf.d/50unattended-upgrades'
    regexp: "{{ item.regexp }}"
    line:   "{{ item.line }}"
  with_items:
  - { regexp: '\$\{distro_codename\}-updates\"\;', line: '    "${distro_id}:${distro_codename}-updates";'         }
  - { regexp: 'InstallOnShutdown',                 line: 'Unattended-Upgrade::InstallOnShutdown "false";'         }
  - { regexp: 'Remove-Unused-Dependencies',        line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";' }
  - { regexp: 'Automatic-Reboot\s',                line: 'Unattended-Upgrade::Automatic-Reboot "true";'           }
  - { regexp: 'Automatic-Reboot-Time',             line: 'Unattended-Upgrade::Automatic-Reboot-Time "02:00";'     }
...
