---
- name: "Install custom SSL certs"
  copy:
    content: "{{ item.data }}"
    dest: "/usr/local/share/ca-certificates/{{ item.filename }}"
    force: "yes"
  with_items: "{{ linux_ssl_certs }}"
  no_log: "yes"
  when: "linux_ssl_certs is defined"
  register: 'ca_certs'

- name: 'Update CA certs'
  command: 'update-ca-certificates -f'
  when: 'ca_certs.changed'
...
